package melo.maiorbrasileirofighter;

public class Lutadores extends javax.swing.JFrame {

    public Lutadores() {
        initComponents();
    }

    BuscaLutador bl = new BuscaLutador();
    
    private String nome;
    private int flagEscolha = 0;
    private String email;
    private String nick;
    private String urlImagem;
    private String urlImagemPlayer;
    private String urlImagemOponente;

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public int getFlagEscolha() {
        return flagEscolha;
    }

    public void setFlagEscolha(int flagEscolha) {
        this.flagEscolha = flagEscolha;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public String getUrlImagem() {
        return urlImagem;
    }

    public void setUrlImagem(String urlImagem) {
        this.urlImagem = urlImagem;
    }

    public String getUrlImagemPlayer() {
        return urlImagemPlayer;
    }

    public void setUrlImagemPlayer(String urlImagemPlayer) {
        this.urlImagemPlayer = urlImagemPlayer;
    }

    public String getUrlImagemOponente() {
        return urlImagemOponente;
    }

    public void setUrlImagemOponente(String urlImagemOponente) {
        this.urlImagemOponente = urlImagemOponente;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagemPersonagem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        imagemPersonagem1 = new javax.swing.JLabel();
        botaoEscolha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Maior Brasileiro Fighter");
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neymar.jpg"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silas.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiririca.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dede.jpg"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dilma.jpg"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atrizrebelde.jpg"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigofaro.jpg"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/micheltelo.jpg"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo.setText("Escolha o seu brasileiro");

        titulo1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        titulo2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        botaoEscolha.setText("Confirma");
        botaoEscolha.setEnabled(false);
        botaoEscolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEscolhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(titulo)
                                        .addGap(33, 33, 33)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton7)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(imagemPersonagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(imagemPersonagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(botaoEscolha)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(imagemPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imagemPersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(titulo)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton5)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(jButton6)
                            .addComponent(jButton8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(botaoEscolha)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setNome("Neymar");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/neymar100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neymarmbf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neymarmbf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setNome("Silas Malafaia");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/silas100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silasmbf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/silasmbf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setNome("Dilma");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/dilma100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dilmambf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dilmambf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setNome("Rodrigo Faro");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/rodrigofaro100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigofarombf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rodrigofarombf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setNome("Tiririca");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/tiririca100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiriricambf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tiriricambf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setNome("Dedé do Vasco");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/dede100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dedembf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dedembf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        setNome("Atriz do Rebelde");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/atrizrebelde100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luablancombf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/luablancombf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        setNome("Michel Teló");
        titulo1.setText(String.valueOf(bl.buscaAtributos(nome).get(4)));
        titulo2.setText(String.valueOf(bl.buscaAtributos(nome).get(5)));
        setUrlImagem("/micheltelo100");
        if (getFlagEscolha() == 0){
            imagemPersonagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/micheltelombf.jpg")));
        } else if (getFlagEscolha() == 1){
            imagemPersonagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/micheltelombf.jpg")));
        }
        botaoEscolha.setEnabled(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    Fighter player;
    Fighter oponente;
    
    private void botaoEscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEscolhaActionPerformed
        // TODO add your handling code here:
        switch (getFlagEscolha()) {
            case 0:
                titulo.setText("Escolha o seu oponente");
                player = bl.buscarLutador(getNome());
                botaoEscolha.setEnabled(false);
                setUrlImagemPlayer(getUrlImagem());
                titulo1.setText("");
                titulo2.setText("");
                setFlagEscolha(1);
                break;
            case 1:
                titulo.setText("");
                oponente = bl.buscarLutador(getNome());
                setUrlImagemOponente(getUrlImagem());
                botaoEscolha.setText("Ir para a batalha");
                titulo1.setText(player.getNome() + " vs.");
                titulo2.setText(oponente.getNome());
                setFlagEscolha(2);
                break;
            case 2:
                Fight f = new Fight();
                f.setEmail(getEmail());
                f.setNick(getNick());
                f.setPlayer(player);            
                f.setOponente(oponente);
                f.setUrlImagemPlayer(getUrlImagemPlayer());
                f.setUrlImagemOponente(getUrlImagemOponente());
                f.setVisible(true);
                dispose();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_botaoEscolhaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lutadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lutadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEscolha;
    private javax.swing.JLabel imagemPersonagem;
    private javax.swing.JLabel imagemPersonagem1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel titulo1;
    private javax.swing.JLabel titulo2;
    // End of variables declaration//GEN-END:variables
}
